name: Auto-merge develop into main
on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest
    # if: ${{ github.actor == 'github-actions[bot]' }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Merge develop into main
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
          git checkout main
          git merge --no-ff develop
          git push origin main
